name: Update Data Files via PR

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggers

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4
        with:
          repository: YOUR_USERNAME/wallets-playbook
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          path: public-repo
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          cd public-repo
          npm install
      
      - name: Fetch data from Airtable
        run: |
          cd public-repo
          npm run fetch-airtable
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_PARTNERS_BASE_ID: ${{ secrets.AIRTABLE_PARTNERS_BASE_ID }}
          AIRTABLE_DEFI_BASE_ID: ${{ secrets.AIRTABLE_DEFI_BASE_ID }}
      
      - name: Build data files
        run: |
          cd public-repo
          npm run build-all-data
      
      - name: Check for changes
        id: check-changes
        run: |
          cd public-repo
          git add -A
          git diff --staged --quiet || echo "has-changes=true" >> $GITHUB_OUTPUT
      
      - name: Create Pull Request
        if: steps.check-changes.outputs.has-changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          path: public-repo
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          commit-message: "🤖 Auto-update data files from Airtable"
          title: "🤖 Auto-update data files from Airtable"
          body: |
            This PR updates the data files with the latest information from Airtable.
            
            **Files updated:**
            - assets.json
            - ramps.json  
            - exchanges.json
            - defi.json
            
            **Generated at:** $(date -u)
            
            Please review the changes before merging.
          branch: auto-update-data
          delete-branch: true
          labels: |
            automated
            data-update 